const KEY="jushenpu-nav-v1", BACKGROUND_KEY="jushenpu-background-v1";
const defaults={recent:[["腾讯视频","T","https://v.qq.com"],["百度云","B","https://pan.baidu.com"],["设计导航","✦","https://hao.uisdc.com"],["MonkeyCode","M","https://monkeycode-ai.com"],["GitHub","G","https://github.com"],["小红书","X","https://www.xiaohongshu.com"],["阿里云","A","https://www.aliyun.com"],["Adobe Stock","S","https://stock.adobe.com"],["Figma","F","https://www.figma.com"],["ChatGPT","G","https://chatgpt.com"]],vertical:[{name:"休闲娱乐",sites:[["Deepseek","D","chat.deepseek.com"],["豆包","豆","doubao.com"],["MonkeyCode 智能开发平台","M","monkeycode-ai.com"],["最好的AI导航站","✦","toolify.ai"],["figma","F","figma.com"]]},{name:"AI 工具",sites:[["Stitch","S","stitch.withgoogle.com"],["Gemini","✦","gemini.google.com"],["天蝎API","A","tianyuai.lol"],["4sapi API","4","4sapi.com"],["APIDot","P","apidot.ai"]]},{name:"设计资源",sites:[["魔戒VPN","◌","mojie.me"],["Proton","◆","account.protonvpn.com"],["字体日记","字","ziti.orji.cn"],["设计导航","◇","hao.shejis.cn"],["figmaEX","◇","moony.com"]]}],footer:[{name:"休闲娱乐",sites:[["硬核影视","H","https://yingheys.com"],["白嫖者联盟","B","https://www.bpzhe.com"],["爱奇艺","iQIYI","https://www.iqiyi.com"],["腾讯视频","▶","https://v.qq.com"],["优酷","YOUKU","https://www.youku.com"],["追影影视","Z","https://www.zhuiying.com"],["广长资源","G","https://www.gzycw.com"],["VIP免费视频","V","https://www.vipmianfei.com"],["蚂蚁影视","M","https://www.mayiyingshi.com"],["娜娜TV","N","https://www.nanatv.com"]]}],hot:["成都一地路面漏电170伏电到宠物狗 446.8万","曝韩国足协为外籍裁判员安排色情招待435.6万","成都一地路面漏电170伏电到宠物狗 446.8万","曝韩国足协为外籍裁判员安排色情招待435.6万","北京雨后又现双彩虹 425.6万","立秋的仪式感 417.9万","东航航班：提前14天可免费退改签 409.2万"]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaults, backgroundState=JSON.parse(localStorage.getItem(BACKGROUND_KEY)||"null")||{type:"color",value:""}, currentEngine="https://www.baidu.com/s?wd=", editing=null, hotItems=data.hot.map(title=>({title,score:""})), hotPage=0;
let dragState=null, editingGroup=null;
const $=s=>document.querySelector(s), urlOf=u=>u.startsWith("http")?u:"https://"+u, favicon=u=>`https://www.google.com/s2/favicons?domain=${encodeURIComponent(u)}&sz=64`;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function groupIcon(name){const value=name.toLowerCase();if(/ai|智能|工具/.test(value))return "fa-wand-magic-sparkles";if(/设计|资源/.test(value))return "fa-pen-ruler";if(/影音|娱乐|休闲|影视/.test(value))return "fa-film";if(/工作|办公/.test(value))return "fa-briefcase";if(/开发|代码/.test(value))return "fa-code";return "fa-folder"}
function groupIconMarkup(group){return group.icon?`<img class="group-custom-icon" src="${group.icon}" alt="">`:`<i class="fa-solid ${groupIcon(group.name)}"></i>`}
function groupActions(kind,index,allowDelete=true){return `<span class="group-actions"><button class="edit-group" data-group-action="edit" data-group-kind="${kind}" data-group-index="${index}" title="编辑分组"><i class="fa-regular fa-pen-to-square"></i></button>${allowDelete?`<button class="delete-group" data-group-action="delete" data-group-kind="${kind}" data-group-index="${index}" title="删除分组"><i class="fa-regular fa-trash-can"></i></button>`:""}</span>`}
function fallbackColor(item){let hash=0;for(const char of item[0])hash=(hash*31+char.charCodeAt(0))&0xffff;return `hsl(${hash%360} 72% 60%)`}
function iconMarkup(item){const icon=item[3]||favicon(item[2]);return `<img src="${icon}" alt="" onload="this.nextElementSibling.style.display='none'" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><b class="letter-icon" style="display:grid;background:${fallbackColor(item)}">${item[0].trim().charAt(0).toUpperCase()}</b>`}
function actionButtons(kind,group,index){return `<span class="site-actions"> <button class="edit-site" data-edit-kind="${kind}" data-edit-group="${group}" data-edit-index="${index}" title="编辑网址"><i class="fa-regular fa-pen-to-square"></i></button><button class="delete-site" data-delete-kind="${kind}" data-delete-group="${group}" data-delete-index="${index}" title="删除网址"><i class="fa-regular fa-trash-can"></i></button></span>`}
function renderSite(item,kind,group,index){return `<a class="site" draggable="true" data-drag-kind="${kind}" data-drag-group="${group}" data-drag-index="${index}" href="${urlOf(item[2])}" target="_blank" rel="noreferrer"><span class="site-icon">${iconMarkup(item)}</span><span class="site-copy"><span class="site-name">${item[0]}</span><span class="site-url">${item[2].replace(/^https?:\/\//,"")}</span></span>${actionButtons(kind,group,index)}</a>`}
function render(){
  $("#recentList").innerHTML=data.recent.map((x,i)=>`<a class="recent-item" href="${urlOf(x[2])}" target="_blank" rel="noreferrer"><span class="recent-icon">${iconMarkup(x)}</span><span>${x[0]}</span></a>`).join("");
  $("#verticalGroups").innerHTML=data.vertical.map((g,gi)=>`<article class="group" data-drop-kind="vertical" data-drop-group="${gi}"><h2>${groupIconMarkup(g)}<span>${g.name}</span>${groupActions("vertical",gi,false)}</h2><div class="site-list">${g.sites.map((x,i)=>renderSite(x,"vertical",gi,i)).join("")}</div></article>`).join("");
  $("#footerGroups").innerHTML=data.footer.map((g,gi)=>`<section class="footer-section" data-drop-kind="footer" data-drop-group="${gi}"><h2 class="footer-title" draggable="true" data-group-drag-index="${gi}">${groupIconMarkup(g)}<span>${g.name}</span>${groupActions("footer",gi)}</h2><div class="footer-grid">${g.sites.map((x,i)=>`<a class="footer-site" draggable="true" data-drag-kind="footer" data-drag-group="${gi}" data-drag-index="${i}" href="${urlOf(x[2])}" target="_blank" rel="noreferrer"><span class="site-icon">${iconMarkup(x)}</span><div><b>${x[0]}</b><small>${x[2].replace(/^https?:\/\//,"")}</small></div>${actionButtons("footer",gi,i)}</a>`).join("")}</div></section>`).join("");
  renderHot();
  $("#siteGroup").innerHTML=[...data.vertical,...data.footer].map(g=>`<option value="${g.name}">${g.name}</option>`).join("")+`<option value="__new__">＋ 新增分类</option>`;
}
function renderHot(){const pageSize=8,start=hotPage*pageSize,items=hotItems.slice(start,start+pageSize);$("#hotList").innerHTML=items.length?items.map((x,i)=>{const rank=start+i+1;return `<div class="hot-row"><span class="hot-rank hot-rank-${rank<=3?rank:"n"}">${rank}</span><a class="hot-title" href="${x.url||"https://www.baidu.com/s?wd="+encodeURIComponent(x.title)}" target="_blank" rel="noreferrer"><span class="hot-title-text">${x.title}</span>${x.tag?`<span class="hot-tag hot-tag-${x.tag==="新"?"new":"hot"}">${x.tag}</span>`:""}</a>${x.score?`<span class="hot-score">${x.score}</span>`:""}</div>`}).join(""):"<div class=\"hot-loading\">暂无更多热点</div>";$("#hotPrev").disabled=hotPage===0;$("#hotNext").disabled=start+pageSize>=hotItems.length}
const HOT_ENDPOINTS=["/api/hot","https://top.baidu.com/api/board?platform=pc&tab=realtime","https://api.allorigins.win/raw?url="+encodeURIComponent("https://top.baidu.com/api/board?platform=pc&tab=realtime"),"https://corsproxy.io/?url="+encodeURIComponent("https://top.baidu.com/api/board?platform=pc&tab=realtime")];
const HOT_TAG_MAP={"1":"新","3":"热"};
function parseHot(payload){const raw=payload?.data?.cards?.flatMap(card=>card.content||[])||[];return raw.map(item=>({title:item.word||item.desc||item.query||"",score:item.hotScore||item.hotChange||item.score||"",url:item.appUrl||item.url||item.rawUrl||"",tag:HOT_TAG_MAP[item.hotTag]||""})).filter(item=>item.title)}
async function loadHot(){const refresh=$("#hotRefresh");refresh.classList.add("is-loading");for(const endpoint of HOT_ENDPOINTS){try{const response=await fetch(endpoint,{cache:"no-store"});if(!response.ok)throw new Error("hot feed unavailable");const parsed=parseHot(await response.json());if(parsed.length){hotItems=parsed.sort((a,b)=>Number(b.score||0)-Number(a.score||0));hotPage=0;renderHot();break}}catch(error){}}hotItems=hotItems.length?hotItems:data.hot.map(title=>({title,score:""}));renderHot();refresh.classList.remove("is-loading")}
function updateClock(){const d=new Date();$("#clock").textContent=[d.getHours(),d.getMinutes(),d.getSeconds()].map(v=>String(v).padStart(2,"0")).join(":");$("#date").textContent=`${d.getFullYear()}年${String(d.getMonth()+1).padStart(2,"0")}月${String(d.getDate()).padStart(2,"0")}日 ${["星期日","星期一","星期二","星期三","星期四","星期五","星期六"][d.getDay()]}`}
function randomGradient(){const h=Math.floor(Math.random()*360),s=32+Math.floor(Math.random()*26),l=40+Math.floor(Math.random()*22),h2=(h+150+Math.floor(Math.random()*60))%360,a=Math.floor(Math.random()*360);return `linear-gradient(${a}deg,hsl(${h},${s}%,${l}%) 0%,hsl(${h2},${s}%,${l+8}%) 100%)`}
function applyBackground(){const hero=$("#hero");hero.classList.remove("warm");hero.style.background="";hero.style.backgroundImage="";hero.style.backgroundSize="";hero.style.backgroundPosition="";hero.style.backgroundRepeat="";if(backgroundState.type==="color"&&backgroundState.value){hero.style.background=backgroundState.value}else if(backgroundState.type==="bing"&&backgroundState.value){hero.style.backgroundImage=`url('${backgroundState.value}')`;hero.style.backgroundSize="cover";hero.style.backgroundPosition="center";hero.style.backgroundRepeat="no-repeat"}else if(backgroundState.type==="upload"){hero.style.backgroundImage=`url("${backgroundState.value}")`;hero.style.backgroundSize="cover";hero.style.backgroundPosition="center";hero.style.backgroundRepeat="no-repeat"}document.querySelectorAll(".background-option").forEach(b=>b.classList.toggle("selected",b.dataset.background===backgroundState.type))}
$("#searchTabs").addEventListener("click",e=>{if(e.target.tagName!=="BUTTON")return;document.querySelectorAll(".search-tabs button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");currentEngine=e.target.dataset.engine;$("#searchInput").placeholder=`在${e.target.textContent}中搜索`});
$("#searchForm").addEventListener("submit",e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(q)window.open(currentEngine+encodeURIComponent(q),"_blank")});
function openAdd(){editing=null;$("#editDialogTitle").textContent="新增网址";$("#editForm").reset();$("#newGroupName").classList.remove("visible");$("#editDialog").showModal()}
function openEdit(kind,group,index){editing={kind,group,index};const item=data[kind][group].sites[index];$("#editDialogTitle").textContent="编辑网址";$("#siteName").value=item[0];$("#siteUrl").value=item[2];$("#siteGroup").value=data[kind][group].name;$("#newGroupName").classList.remove("visible");$("#editDialog").showModal()}
$("#siteGroup").addEventListener("change",e=>$("#newGroupName").classList.toggle("visible",e.target.value==="__new__"));
$("#editForm").addEventListener("submit",e=>{e.preventDefault();const name=$("#siteName").value.trim(),url=$("#siteUrl").value.trim(),selected=$("#siteGroup").value,newName=$("#newGroupName").value.trim(),file=$("#siteIconFile").files[0];if(!name||!url)return;let groupName=selected;if(selected==="__new__"){if(!newName){$("#newGroupName").focus();return}groupName=newName;data.footer.push({name:groupName,sites:[]})}const target=[...data.vertical,...data.footer].find(g=>g.name===groupName);if(!target)return;const finish=icon=>{const original=editing?data[editing.kind][editing.group].sites[editing.index]:null;const item=[name,name.slice(0,1).toUpperCase(),url,icon||original?.[3]||favicon(url)];if(editing){data[editing.kind][editing.group].sites.splice(editing.index,1);target.sites.push(item);data.recent=data.recent.map(x=>x[2]===original[2]?item:x)}else{target.sites.push(item);data.recent.unshift(item);data.recent=data.recent.slice(0,10)}save();render();$("#editDialog").close();$("#editForm").reset();editing=null};if(file){const reader=new FileReader();reader.onload=()=>finish(reader.result);reader.readAsDataURL(file)}else finish()});
$("#cancelEdit").addEventListener("click",()=>{$("#editDialog").close();editing=null});
function openGroupEdit(kind,index){editingGroup={kind,index};const group=data[kind][index];$("#groupName").value=group.name;$("#groupIconFile").value="";$("#groupDialog").showModal()}
$("#cancelGroupEdit").addEventListener("click",()=>{$("#groupDialog").close();editingGroup=null});
$("#groupForm").addEventListener("submit",e=>{e.preventDefault();if(!editingGroup)return;const group=data[editingGroup.kind][editingGroup.index],name=$("#groupName").value.trim(),file=$("#groupIconFile").files[0];if(!name)return;const finish=icon=>{group.name=name;if(icon)group.icon=icon;save();render();$("#groupDialog").close();editingGroup=null};if(file){const reader=new FileReader();reader.onload=()=>finish(reader.result);reader.readAsDataURL(file)}else finish(group.icon)});
$(".floating-tools").addEventListener("click",e=>{const button=e.target.closest("button"),action=button?.dataset.action;if(!action)return;if(action==="add")openAdd();if(action==="edit"){document.body.classList.toggle("edit-mode");button.classList.toggle("active")}if(action==="theme")$("#backgroundDialog").showModal();if(action==="clear"&&confirm("确定清空所有网址吗？")){data={...data,recent:[],vertical:data.vertical.map(g=>({...g,sites:[]})),footer:data.footer.map(g=>({...g,sites:[]}))};save();render()}if(action==="export"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="幸福海导航备份.json";a.click()}if(action==="restore"||action==="import")$("#fileInput").click()});
document.addEventListener("click",e=>{const b=e.target.closest(".edit-site");if(!b||!document.body.classList.contains("edit-mode"))return;e.preventDefault();e.stopPropagation();openEdit(b.dataset.editKind,Number(b.dataset.editGroup),Number(b.dataset.editIndex))});
document.addEventListener("click",e=>{const b=e.target.closest("[data-group-action]");if(!b||!document.body.classList.contains("edit-mode"))return;e.preventDefault();e.stopPropagation();const kind=b.dataset.groupKind,index=Number(b.dataset.groupIndex);if(b.dataset.groupAction==="edit")openGroupEdit(kind,index);if(b.dataset.groupAction==="delete"&&confirm("确定删除这个分组及其中的网址吗？")){const removed=data[kind][index].sites.map(x=>x[2]);data[kind].splice(index,1);data.recent=data.recent.filter(x=>!removed.includes(x[2]));save();render()}});
document.addEventListener("click",e=>{const b=e.target.closest(".delete-site");if(!b)return;e.preventDefault();e.stopPropagation();const kind=b.dataset.deleteKind,group=Number(b.dataset.deleteGroup),index=Number(b.dataset.deleteIndex),list=data[kind][group].sites,removed=list[index];if(confirm("确定删除这个网址吗？")){list.splice(index,1);data.recent=data.recent.filter(x=>x[2]!==removed?.[2]);save();render()}});
$("#backgroundDialog").addEventListener("click",e=>{const option=e.target.closest(".background-option");if(!option)return;const type=option.dataset.background;if(type==="upload"){$("#backgroundInput").click();return}if(type==="bing"){fetch("/api/bing").then(r=>r.json()).then(d=>{if(d.url){backgroundState.type="bing";backgroundState.value=d.url;localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()}}).catch(()=>{const u="https://www.bing.com/th?id=OHR.BingDaily_1920x1080.jpg&pid=hp";backgroundState.type="bing";backgroundState.value=u;localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()});return}backgroundState.type=type;backgroundState.value=type==="color"?randomGradient():Date.now();localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()});
$("#backgroundInput").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{backgroundState.type="upload";backgroundState.value=reader.result;localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()};reader.readAsDataURL(file);e.target.value=""});
document.querySelectorAll("#closeBackground,#closeBackgroundBottom").forEach(button=>button.addEventListener("click",()=>$("#backgroundDialog").close()));
$("#hotPrev").addEventListener("click",()=>{if(hotPage>0){hotPage--;renderHot()}});
$("#hotNext").addEventListener("click",()=>{if((hotPage+1)*8<hotItems.length){hotPage++;renderHot()}});
$("#hotRefresh").addEventListener("click",loadHot);
$("#fileInput").addEventListener("change", function(e){
  const file=e.target.files[0]; if(!file)return;
  const reader=new FileReader();
  reader.onload=function(){
    let parsed;
    try{parsed=JSON.parse(reader.result)}catch{parsed=null}
    if(parsed&&parsed.vertical&&parsed.footer){data=parsed;save();render();alert("备份已还原");e.target.value="";return}
    const doc=new DOMParser().parseFromString(reader.result,"text/html"), groups=[];
    doc.querySelectorAll("h3").forEach(h3=>{const group={name:h3.textContent.trim()||"导入收藏",sites:[]};const dl=h3.nextElementSibling?.tagName==="DL"?h3.nextElementSibling:h3.parentElement?.querySelector(":scope > dl");dl?.querySelectorAll(":scope > dt > a[href]").forEach(a=>group.sites.push([a.textContent.trim()||a.href,"·",a.href]));if(group.sites.length)groups.push(group)});
    if(!groups.length){const links=[...doc.querySelectorAll("a[href]")].map(a=>[a.textContent.trim()||a.href,"·",a.href]);if(links.length)groups.push({name:"导入收藏",sites:links})}
    if(groups.length){data.footer.push(...groups);save();render();alert(`已导入 ${groups.reduce((n,g)=>n+g.sites.length,0)} 个网址`)}
    e.target.value="";
  };
  reader.readAsText(file);
});
document.addEventListener("dragstart",e=>{if(!document.body.classList.contains("edit-mode")){e.preventDefault();return}const site=e.target.closest("[data-drag-kind]");const title=e.target.closest("[data-group-drag-index]");if(site){dragState={type:"site",kind:site.dataset.dragKind,group:Number(site.dataset.dragGroup),index:Number(site.dataset.dragIndex)};site.classList.add("dragging")}else if(title&&title.closest(".footer-section")){dragState={type:"group",index:Number(title.dataset.groupDragIndex)};title.closest(".footer-section").classList.add("dragging")}});
document.addEventListener("dragover",e=>{if(!dragState)return;const target=e.target.closest("[data-drop-kind]");if(!target)return;e.preventDefault();document.querySelectorAll(".drop-target").forEach(el=>el.classList.remove("drop-target"));target.classList.add("drop-target")});
document.addEventListener("drop",e=>{if(!dragState)return;const target=e.target.closest("[data-drop-kind]");if(!target)return;e.preventDefault();const targetKind=target.dataset.dropKind,targetGroup=Number(target.dataset.dropGroup);if(dragState.type==="group"&&targetKind==="footer"){const moved=data.footer.splice(dragState.index,1)[0];let at=targetGroup;if(dragState.index<targetGroup)at--;data.footer.splice(Math.max(0,at),0,moved)}else if(dragState.type==="site"){const source=data[dragState.kind][dragState.group]?.sites;const destination=data[targetKind][targetGroup]?.sites;if(source&&destination){const moved=source.splice(dragState.index,1)[0];const overSite=e.target.closest("[data-drag-kind]");let at=destination.length;if(overSite&&overSite.dataset.dragKind===targetKind&&Number(overSite.dataset.dragGroup)===targetGroup)at=Number(overSite.dataset.dragIndex);if(source===destination&&dragState.index<at)at--;destination.splice(Math.max(0,at),0,moved)}}dragState=null;document.querySelectorAll(".drop-target,.dragging").forEach(el=>el.classList.remove("drop-target","dragging"));save();render()});
document.addEventListener("dragend",()=>{dragState=null;document.querySelectorAll(".drop-target,.dragging").forEach(el=>el.classList.remove("drop-target","dragging"))});
document.addEventListener("click",e=>{const link=e.target.closest(".site,.footer-site,.recent-item");if(!link||!link.href||link.href.startsWith("javascript:")||link.closest(".site-actions,.group-actions"))return;const name=link.querySelector(".site-name")?.textContent||link.querySelector("b")?.textContent||link.querySelector("span:last-child")?.textContent||"";const url=link.href;if(!name||!url)return;data.recent=data.recent.filter(x=>x[2]!==url);data.recent.unshift([name,name.slice(0,1).toUpperCase(),url]);data.recent=data.recent.slice(0,10);save();render()});
render();applyBackground();updateClock();setInterval(updateClock,1000);loadHot();
