const KEY="jushenpu-nav-v1", BACKGROUND_KEY="jushenpu-background-v1";
const defaults={recent:[["腾讯视频","T","https://v.qq.com"],["百度云","B","https://pan.baidu.com"],["设计导航","✦","https://hao.uisdc.com"],["MonkeyCode","M","https://monkeycode-ai.com"],["GitHub","G","https://github.com"],["小红书","X","https://www.xiaohongshu.com"],["阿里云","A","https://www.aliyun.com"],["Adobe Stock","S","https://stock.adobe.com"],["Figma","F","https://www.figma.com"],["ChatGPT","G","https://chatgpt.com"]],vertical:[{name:"休闲娱乐",sites:[["Deepseek","D","chat.deepseek.com"],["豆包","豆","doubao.com"],["MonkeyCode 智能开发平台","M","monkeycode-ai.com"],["最好的AI导航站","✦","toolify.ai"],["figma","F","figma.com"]]},{name:"AI 工具",sites:[["Stitch","S","stitch.withgoogle.com"],["Gemini","✦","gemini.google.com"],["天蝎API","A","tianyuai.lol"],["4sapi API","4","4sapi.com"],["APIDot","P","apidot.ai"]]},{name:"设计资源",sites:[["魔戒VPN","◌","mojie.me"],["Proton","◆","account.protonvpn.com"],["字体日记","字","ziti.orji.cn"],["设计导航","◇","hao.shejis.cn"],["figmaEX","◇","moony.com"]]}],footer:[{name:"休闲娱乐",sites:[["硬核影视","H","https://yingheys.com"],["白嫖者联盟","B","https://www.bpzhe.com"],["爱奇艺","iQIYI","https://www.iqiyi.com"],["腾讯视频","▶","https://v.qq.com"],["优酷","YOUKU","https://www.youku.com"],["追影影视","Z","https://www.zhuiying.com"],["广长资源","G","https://www.gzycw.com"],["VIP免费视频","V","https://www.vipmianfei.com"],["蚂蚁影视","M","https://www.mayiyingshi.com"],["娜娜TV","N","https://www.nanatv.com"]]}],hot:["成都一地路面漏电170伏电到宠物狗 446.8万","曝韩国足协为外籍裁判员安排色情招待435.6万","成都一地路面漏电170伏电到宠物狗 446.8万","曝韩国足协为外籍裁判员安排色情招待435.6万","北京雨后又现双彩虹 425.6万","立秋的仪式感 417.9万","东航航班：提前14天可免费退改签 409.2万"]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaults, backgroundState=JSON.parse(localStorage.getItem(BACKGROUND_KEY)||"null")||{type:"color",value:""}, currentEngine="https://www.baidu.com/s?wd=", editing=null, hotItems=data.hot.map(title=>({title,score:""})), hotPage=0;
let dragState=null, editingGroup=null;
const $=s=>document.querySelector(s), urlOf=u=>u.startsWith("http")?u:"https://"+u, favicon=u=>`https://www.google.com/s2/favicons?domain=${encodeURIComponent(u)}&sz=64`;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function allGroups(){return [...data.vertical,...data.footer]}
function hasGroupName(name,ignore){return allGroups().some(group=>group!==ignore&&group.name.trim().toLowerCase()===name.trim().toLowerCase())}
function mergeGroups(groups){groups.forEach(incoming=>{const existing=allGroups().find(group=>group.name.trim().toLowerCase()===incoming.name.trim().toLowerCase());if(existing)existing.sites.push(...incoming.sites);else data.footer.push(incoming)})}
function groupIcon(name){const value=name.toLowerCase();if(/ai|智能|工具/.test(value))return "fa-wand-magic-sparkles";if(/设计|资源/.test(value))return "fa-pen-ruler";if(/影音|娱乐|休闲|影视/.test(value))return "fa-film";if(/工作|办公/.test(value))return "fa-briefcase";if(/开发|代码/.test(value))return "fa-code";return "fa-folder"}
function groupIconMarkup(group){return group.icon?`<img class="group-custom-icon" src="${group.icon}" alt="">`:`<i class="fa-solid ${groupIcon(group.name)}"></i>`}
function groupActions(kind,index,allowDelete=true){return `<span class="group-actions"><button class="edit-group" data-group-action="edit" data-group-kind="${kind}" data-group-index="${index}" title="编辑分组"><i class="fa-regular fa-pen-to-square"></i></button>${allowDelete?`<button class="delete-group" data-group-action="delete" data-group-kind="${kind}" data-group-index="${index}" title="删除分组"><i class="fa-regular fa-trash-can"></i></button>`:""}</span>`}
function fallbackColor(item){let hash=0;for(const char of item[0])hash=(hash*31+char.charCodeAt(0))&0xffff;return `hsl(${hash%360} 72% 60%)`}
function iconMarkup(item){const icon=item[3]||favicon(item[2]);return `<img src="${icon}" alt="" onload="this.nextElementSibling.style.display='none'" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><b class="letter-icon" style="display:grid;background:${fallbackColor(item)}">${item[0].trim().charAt(0).toUpperCase()}</b>`}
function actionButtons(kind,group,index){return `<span class="site-actions"> <button class="edit-site" data-edit-kind="${kind}" data-edit-group="${group}" data-edit-index="${index}" title="编辑网址"><i class="fa-regular fa-pen-to-square"></i></button><button class="delete-site" data-delete-kind="${kind}" data-delete-group="${group}" data-delete-index="${index}" title="删除网址"><i class="fa-regular fa-trash-can"></i></button></span>`}
function renderSite(item,kind,group,index){return `<a class="site" draggable="true" data-drag-kind="${kind}" data-drag-group="${group}" data-drag-index="${index}" href="${urlOf(item[2])}" target="_blank" rel="noreferrer"><span class="site-icon">${iconMarkup(item)}</span><span class="site-copy"><span class="site-name">${item[0]}</span><span class="site-url">${item[2].replace(/^https?:\/\//,"")}</span></span>${actionButtons(kind,group,index)}</a>`}
function render(){
  $("#recentList").innerHTML=data.recent.map((x,i)=>`<a class="recent-item" href="${urlOf(x[2])}" target="_blank" rel="noreferrer"><span class="recent-icon">${iconMarkup(x)}</span><span>${x[0]}</span></a>`).join("");
  $("#verticalGroups").innerHTML=data.vertical.map((g,gi)=>`<article class="group" data-drop-kind="vertical" data-drop-group="${gi}"><h2>${groupIconMarkup(g)}<span>${g.name}</span>${groupActions("vertical",gi,false)}</h2><div class="site-list">${g.sites.map((x,i)=>renderSite(x,"vertical",gi,i)).join("")}</div></article>`).join("");
  $("#footerGroups").innerHTML=data.footer.map((g,gi)=>`<section class="footer-section" data-drop-kind="footer" data-drop-group="${gi}"><h2 class="footer-title" draggable="true" data-group-drag-index="${gi}">${groupIconMarkup(g)}<span>${g.name}</span>${groupActions("footer",gi)}</h2><div class="footer-grid">${g.sites.map((x,i)=>`<a class="footer-site" draggable="true" data-drag-kind="footer" data-drag-group="${gi}" data-drag-index="${i}" href="${urlOf(x[2])}" target="_blank" rel="noreferrer"><span class="site-icon">${iconMarkup(x)}</span><div><b>${x[0]}</b><small>${x[2].replace(/^https?:\/\//,"")}</small></div>${actionButtons("footer",gi,i)}</a>`).join("")}</div></section>`).join("");
  renderHot();
  $("#siteGroup").innerHTML=[...data.vertical,...data.footer].map(g=>`<option value="${g.name}">${g.name}</option>`).join("")+`<option value="__new__">＋ 新增分类</option>`;
}
function renderHot(){const pageSize=7,start=hotPage*pageSize,items=hotItems.slice(start,start+pageSize);$("#hotList").innerHTML=items.length?items.map((x,i)=>`<div class="hot-row"><span class="hot-rank">${start+i+1}</span><span>${x.title}</span>${x.score?`<span class="hot-score">${x.score}</span>`:""}</div>`).join(""):"<div class=\"hot-loading\">暂无更多热点</div>";$("#hotPrev").disabled=hotPage===0;$("#hotNext").disabled=start+pageSize>=hotItems.length}
function normalizeHot(payload){const raw=payload?.data?.cards?.flatMap(card=>card.content||[])||payload?.data?.list||payload?.data||[];return Array.isArray(raw)?raw.map(item=>({title:item.word||item.desc||item.query||item.title||item.name||item.keyword||"",score:item.hotScore||item.hotChange||item.score||item.index||item.hot||item.hot_value||item.hotnum||""})).filter(item=>item.title):[]}
function parseHotHtml(text){const doc=new DOMParser().parseFromString(text,"text/html"),seen=new Set(),items=[];doc.querySelectorAll("a").forEach(anchor=>{const title=anchor.textContent.replace(/\s+/g," ").trim();if(title.length<5||title.length>80||seen.has(title)||/百度|登录|下载|首页|更多|新闻|热搜榜/.test(title))return;seen.add(title);items.push({title,score:String(100000-items.length)})});return items}
async function requestHot(url){const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("hot feed unavailable");const text=await response.text();try{const parsed=normalizeHot(JSON.parse(text));if(parsed.length)return parsed}catch{}return parseHotHtml(text)}
async function loadHot(){const refresh=$("#hotRefresh");refresh.classList.add("is-loading");try{const parsed=await requestHot("/api/hot");if(parsed.length){hotItems=parsed.sort((a,b)=>Number(b.score||0)-Number(a.score||0));hotPage=0;renderHot()}}catch{if(!hotItems.length)renderHot()}finally{refresh.classList.remove("is-loading")}}
function updateClock(){const now=new Date();$("#clock").textContent=[now.getHours(),now.getMinutes(),now.getSeconds()].map(v=>String(v).padStart(2,"0")).join(":");$("#date").textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",weekday:"long"}).format(now).replaceAll("/","年").replace("年","年").replace("年","年")}
function saveBingDataUrl(dataUrl){backgroundState.value=dataUrl;localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));$("#hero").style.backgroundImage=`url("${dataUrl}")`;$("#hero").classList.add("has-image")}
async function loadBingBackground(){return}
function applyBackground(){const hero=$("#hero"),hasCachedBing=backgroundState.type==="bing"&&typeof backgroundState.value==="string"&&(backgroundState.value.startsWith("data:image/")||backgroundState.value.startsWith("http"));hero.classList.toggle("warm",backgroundState.type==="color"&&backgroundState.value==="warm");hero.classList.toggle("has-image",backgroundState.type!=="color");if(backgroundState.type==="upload"||hasCachedBing)hero.style.backgroundImage=`url("${backgroundState.value}")`;else if(backgroundState.type==="bing")loadBingBackground();else hero.style.backgroundImage="";document.querySelectorAll(".background-option").forEach(b=>b.classList.toggle("selected",b.dataset.background===backgroundState.type))}
$("#searchTabs").addEventListener("click",e=>{if(e.target.tagName!=="BUTTON")return;document.querySelectorAll(".search-tabs button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");currentEngine=e.target.dataset.engine;$("#searchInput").placeholder=`在${e.target.textContent}中搜索`});
$("#searchForm").addEventListener("submit",e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(q)window.open(currentEngine+encodeURIComponent(q),"_blank")});
function openAdd(){editing=null;$("#editDialogTitle").textContent="新增网址";$("#editForm").reset();$("#newGroupName").classList.remove("visible");$("#editDialog").showModal()}
function openEdit(kind,group,index){editing={kind,group,index};const item=data[kind][group].sites[index];$("#editDialogTitle").textContent="编辑网址";$("#siteName").value=item[0];$("#siteUrl").value=item[2];$("#siteGroup").value=data[kind][group].name;$("#newGroupName").classList.remove("visible");$("#editDialog").showModal()}
$("#siteGroup").addEventListener("change",e=>$("#newGroupName").classList.toggle("visible",e.target.value==="__new__"));
$("#editForm").addEventListener("submit",e=>{e.preventDefault();const name=$("#siteName").value.trim(),url=$("#siteUrl").value.trim(),selected=$("#siteGroup").value,newName=$("#newGroupName").value.trim(),file=$("#siteIconFile").files[0];if(!name||!url)return;let groupName=selected;if(selected==="__new__"){if(!newName){$("#newGroupName").focus();return}if(hasGroupName(newName)){alert("分组名称已存在，请使用其他名称");return}groupName=newName;data.footer.push({name:groupName,sites:[]})}const target=[...data.vertical,...data.footer].find(g=>g.name===groupName);if(!target)return;const finish=icon=>{const original=editing?data[editing.kind][editing.group].sites[editing.index]:null;const item=[name,name.slice(0,1).toUpperCase(),url,icon||original?.[3]||favicon(url)];if(editing){data[editing.kind][editing.group].sites.splice(editing.index,1);target.sites.push(item);data.recent=data.recent.map(x=>x[2]===original[2]?item:x)}else{target.sites.push(item);data.recent.unshift(item);data.recent=data.recent.slice(0,10)}save();render();$("#editDialog").close();$("#editForm").reset();editing=null};if(file){const reader=new FileReader();reader.onload=()=>finish(reader.result);reader.readAsDataURL(file)}else finish()});
$("#cancelEdit").addEventListener("click",()=>{$("#editDialog").close();editing=null});
function openGroupEdit(kind,index){editingGroup={kind,index};const group=data[kind][index];$("#groupName").value=group.name;$("#groupIconFile").value="";$("#groupDialog").showModal()}
$("#cancelGroupEdit").addEventListener("click",()=>{$("#groupDialog").close();editingGroup=null});
$("#groupForm").addEventListener("submit",e=>{e.preventDefault();if(!editingGroup)return;const group=data[editingGroup.kind][editingGroup.index],name=$("#groupName").value.trim(),file=$("#groupIconFile").files[0];if(!name)return;if(hasGroupName(name,group)){alert("分组名称已存在，请使用其他名称");return}const finish=icon=>{group.name=name;if(icon)group.icon=icon;save();render();$("#groupDialog").close();editingGroup=null};if(file){const reader=new FileReader();reader.onload=()=>finish(reader.result);reader.readAsDataURL(file)}else finish(group.icon)});
$(".floating-tools").addEventListener("click",e=>{const button=e.target.closest("button"),action=button?.dataset.action;if(!action)return;if(action==="add")openAdd();if(action==="edit"){document.body.classList.toggle("edit-mode");button.classList.toggle("active")}if(action==="theme")$("#backgroundDialog").showModal();if(action==="clear"&&confirm("确定清空所有网址吗？")){const protectedNames=new Set(["休闲娱乐","AI 工具","设计资源"]);data={...data,recent:[],vertical:data.vertical.filter(group=>protectedNames.has(group.name)),footer:[]};save();render()}if(action==="export"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="聚神铺导航备份.json";a.click()}if(action==="restore"||action==="import")$("#fileInput").click()});
document.addEventListener("click",e=>{const b=e.target.closest(".edit-site");if(!b||!document.body.classList.contains("edit-mode"))return;e.preventDefault();e.stopPropagation();openEdit(b.dataset.editKind,Number(b.dataset.editGroup),Number(b.dataset.editIndex))});
document.addEventListener("click",e=>{const b=e.target.closest("[data-group-action]");if(!b||!document.body.classList.contains("edit-mode"))return;e.preventDefault();e.stopPropagation();const kind=b.dataset.groupKind,index=Number(b.dataset.groupIndex);if(b.dataset.groupAction==="edit")openGroupEdit(kind,index);if(b.dataset.groupAction==="delete"&&confirm("确定删除这个分组及其中的网址吗？")){const removed=data[kind][index].sites.map(x=>x[2]);data[kind].splice(index,1);data.recent=data.recent.filter(x=>!removed.includes(x[2]));save();render()}});
document.addEventListener("click",e=>{const b=e.target.closest(".delete-site");if(!b)return;e.preventDefault();e.stopPropagation();const kind=b.dataset.deleteKind,group=Number(b.dataset.deleteGroup),index=Number(b.dataset.deleteIndex),list=data[kind][group].sites,removed=list[index];if(confirm("确定删除这个网址吗？")){list.splice(index,1);data.recent=data.recent.filter(x=>x[2]!==removed?.[2]);save();render()}});
$("#backgroundDialog").addEventListener("click",e=>{const option=e.target.closest(".background-option");if(!option)return;const type=option.dataset.background;if(type==="upload"){$("#backgroundInput").click();return}backgroundState.type=type;backgroundState.value="";localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()});
$("#backgroundInput").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{backgroundState.type="upload";backgroundState.value=reader.result;localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()};reader.readAsDataURL(file);e.target.value=""});
document.querySelectorAll("#closeBackground,#closeBackgroundBottom").forEach(button=>button.addEventListener("click",()=>$("#backgroundDialog").close()));
$("#hotPrev").addEventListener("click",()=>{if(hotPage>0){hotPage--;renderHot()}});
$("#hotNext").addEventListener("click",()=>{if((hotPage+1)*7<hotItems.length){hotPage++;renderHot()}});
$("#hotRefresh").addEventListener("click",loadHot);
$("#fileInput").addEventListener("change", function(e){
  const file=e.target.files[0]; if(!file)return;
  const reader=new FileReader();
  reader.onload=function(){
    let parsed;
    try{parsed=JSON.parse(reader.result)}catch{parsed=null}
    if(parsed&&parsed.vertical&&parsed.footer){data=parsed;save();render();alert("备份已还原");e.target.value="";return}
    const doc=new DOMParser().parseFromString(reader.result,"text/html"), groups=[];
    doc.querySelectorAll("h3").forEach(h3=>{const group={name:h3.textContent.trim()||"导入收藏",sites:[]};const dl=h3.nextElementSibling?.tagName==="DL"?h3.nextElementSibling:h3.parentElement?.querySelector(":scope > dl");dl?.querySelectorAll(":scope > dt > a[href]").forEach(a=>group.sites.push([a.textContent.trim()||a.href,"·",a.href]));if(group.sites.length)groups.push(group)});
    if(!groups.length){const links=[...doc.querySelectorAll("a[href]")].map(a=>[a.textContent.trim()||a.href,"·",a.href]);if(links.length)groups.push({name:"导入收藏",sites:links})}
    if(groups.length){mergeGroups(groups);save();render();alert(`已导入 ${groups.reduce((n,g)=>n+g.sites.length,0)} 个网址`)}
    e.target.value="";
  };
  reader.readAsText(file);
});
document.addEventListener("dragstart",e=>{if(!document.body.classList.contains("edit-mode")){e.preventDefault();return}const site=e.target.closest("[data-drag-kind]");const title=e.target.closest("[data-group-drag-index]");if(site){dragState={type:"site",kind:site.dataset.dragKind,group:Number(site.dataset.dragGroup),index:Number(site.dataset.dragIndex)};site.classList.add("dragging")}else if(title&&title.closest(".footer-section")){dragState={type:"group",index:Number(title.dataset.groupDragIndex)};title.closest(".footer-section").classList.add("dragging")}});
document.addEventListener("dragover",e=>{if(!dragState)return;const target=e.target.closest("[data-drop-kind]");if(!target)return;e.preventDefault();document.querySelectorAll(".drop-target").forEach(el=>el.classList.remove("drop-target"));target.classList.add("drop-target")});
document.addEventListener("drop",e=>{if(!dragState)return;const target=e.target.closest("[data-drop-kind]");if(!target)return;e.preventDefault();const targetKind=target.dataset.dropKind,targetGroup=Number(target.dataset.dropGroup);if(dragState.type==="group"&&targetKind==="footer"){const moved=data.footer.splice(dragState.index,1)[0];let at=targetGroup;if(dragState.index<targetGroup)at--;data.footer.splice(Math.max(0,at),0,moved)}else if(dragState.type==="site"){const source=data[dragState.kind][dragState.group]?.sites;const destination=data[targetKind][targetGroup]?.sites;if(source&&destination){const moved=source.splice(dragState.index,1)[0];const overSite=e.target.closest("[data-drag-kind]");let at=destination.length;if(overSite&&overSite.dataset.dragKind===targetKind&&Number(overSite.dataset.dragGroup)===targetGroup)at=Number(overSite.dataset.dragIndex);if(source===destination&&dragState.index<at)at--;destination.splice(Math.max(0,at),0,moved)}}dragState=null;document.querySelectorAll(".drop-target,.dragging").forEach(el=>el.classList.remove("drop-target","dragging"));save();render()});
document.addEventListener("dragend",()=>{dragState=null;document.querySelectorAll(".drop-target,.dragging").forEach(el=>el.classList.remove("drop-target","dragging"))});
render();applyBackground();updateClock();setInterval(updateClock,1000);

// Keep the cached wallpaper on startup; fetch a new image only from the modal action.
function randomGradient(){const hue=Math.floor(Math.random()*360),second=(hue+150+Math.floor(Math.random()*60))%360;return `linear-gradient(${Math.floor(Math.random()*360)}deg,hsl(${hue} 42% 48%),hsl(${second} 42% 56%))`}
applyBackground=function(){const hero=$("#hero");hero.classList.remove("warm","has-image");hero.style.background="";hero.style.backgroundImage="";hero.style.backgroundSize="";hero.style.backgroundPosition="";hero.style.backgroundRepeat="";if(backgroundState.type==="color"&&backgroundState.value){hero.style.background=backgroundState.value}else if((backgroundState.type==="bing"||backgroundState.type==="upload")&&backgroundState.value){hero.classList.add("has-image");hero.style.backgroundImage=`url("${backgroundState.value}")`;hero.style.backgroundSize="cover";hero.style.backgroundPosition="center";hero.style.backgroundRepeat="no-repeat"}document.querySelectorAll(".background-option").forEach(b=>b.classList.toggle("selected",b.dataset.background===backgroundState.type))};
function renderReferenceHot(){const pageSize=8,start=hotPage*pageSize,items=hotItems.slice(start,start+pageSize);$("#hotList").innerHTML=items.length?items.map((item,index)=>{const rank=start+index+1;return `<div class="hot-row"><span class="hot-rank hot-rank-${rank<=3?rank:"n"}">${rank}</span><a class="hot-title" href="${item.url||"https://www.baidu.com/s?wd="+encodeURIComponent(item.title)}" target="_blank" rel="noreferrer"><span class="hot-title-text">${item.title}</span>${item.tag?`<span class="hot-tag hot-tag-${item.tag==="新"?"new":"hot"}">${item.tag}</span>`:""}</a>${item.score?`<span class="hot-score">${item.score}</span>`:""}</div>`}).join(""):"<div class=\"hot-loading\">暂无更多热点</div>";$("#hotPrev").disabled=hotPage===0;$("#hotNext").disabled=start+pageSize>=hotItems.length}
async function loadReferenceHot(){const refresh=$("#hotRefresh");refresh.classList.add("is-loading");try{const response=await fetch("/api/hot",{cache:"no-store"});if(!response.ok)throw new Error("hot feed unavailable");const payload=await response.json();const raw=payload?.data?.cards?.flatMap(card=>card.content||[])||[];const tags={"1":"新","3":"热"};hotItems=raw.map(item=>({title:item.word||item.desc||item.query||"",score:item.hotScore||item.hotChange||item.score||"",url:item.appUrl||item.url||item.rawUrl||"",tag:tags[item.hotTag]||""})).filter(item=>item.title).sort((a,b)=>Number(b.score||0)-Number(a.score||0));hotPage=0;renderReferenceHot()}catch{renderReferenceHot()}finally{refresh.classList.remove("is-loading")}}
document.querySelector("#backgroundDialog").addEventListener("click",e=>{const option=e.target.closest(".background-option");if(!option)return;e.stopImmediatePropagation();const type=option.dataset.background;if(type==="upload"){$("#backgroundInput").click();return}if(type==="bing"){option.disabled=true;option.classList.add("is-loading");fetch("/api/bing",{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error("wallpaper unavailable");return response.json()}).then(result=>{if(!result.url)throw new Error("invalid wallpaper");backgroundState={type:"bing",value:result.url};localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()}).catch(()=>{}).finally(()=>{option.disabled=false;option.classList.remove("is-loading")});return}backgroundState={type:"color",value:randomGradient()};localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()},{capture:true});
document.querySelector("#hotPrev").onclick=()=>{if(hotPage>0){hotPage--;renderReferenceHot()}};document.querySelector("#hotNext").onclick=()=>{if((hotPage+1)*8<hotItems.length){hotPage++;renderReferenceHot()}};document.querySelector("#hotRefresh").onclick=loadReferenceHot;
applyBackground();

// Browser-only mode: use CORS-friendly public feeds and a direct image resource; no local Node API is required.
async function loadBrowserHot(){const refresh=$("#hotRefresh");refresh.classList.add("is-loading");const sources=["https://api.vvhan.com/api/hotlist/baiduRD","https://tenapi.cn/v2/baiduhot","https://r.jina.ai/http://top.baidu.com/board?tab=realtime"];try{let items=[];for(const source of sources){try{const response=await fetch(source,{cache:"no-store"});if(!response.ok)continue;const text=await response.text();let payload;try{payload=JSON.parse(text)}catch{}const raw=payload?.data?.cards?.flatMap(card=>card.content||[])||payload?.data?.list||payload?.data||(Array.isArray(payload)?payload:[]);if(Array.isArray(raw)){items=raw.map(item=>({title:item.word||item.desc||item.query||item.title||item.name||item.keyword||"",score:item.hotScore||item.hotChange||item.hot||item.score||item.index||"",url:item.appUrl||item.url||item.rawUrl||"",tag:item.hotTag==="1"?"新":item.hotTag==="3"?"热":""})).filter(item=>item.title);if(items.length)break}}catch{}}if(items.length){hotItems=items.sort((a,b)=>Number(b.score||0)-Number(a.score||0));hotPage=0}renderReferenceHot()}finally{refresh.classList.remove("is-loading")}}
// Browser-only background handler removed; the Node proxy handler above remains authoritative.
document.querySelector("#hotRefresh").onclick=loadReferenceHot;

const localHotFallback=[...data.hot.map(title=>({title,score:""})),{title:"今日热点资讯精选",score:""},{title:"科技数码行业最新动态",score:""},{title:"社会民生实时关注",score:""},{title:"财经市场重要消息",score:""},{title:"文化娱乐热门话题",score:""},{title:"体育赛事最新进展",score:""},{title:"国际新闻热点速览",score:""}];
if(hotItems.length<9){hotItems=localHotFallback;renderReferenceHot()}
for(const id of ["hotPrev","hotNext","hotRefresh"]){const old=$("#"+id),fresh=old.cloneNode(true);old.replaceWith(fresh)}
$("#hotPrev").addEventListener("click",()=>{if(hotPage>0){hotPage--;renderReferenceHot()}});
$("#hotNext").addEventListener("click",()=>{if((hotPage+1)*8<hotItems.length){hotPage++;renderReferenceHot()}});
$("#hotRefresh").addEventListener("click",loadReferenceHot);

function renderRecent(){
  $("#recentList").innerHTML=data.recent.map(x=>`<a class="recent-item" href="${urlOf(x[2])}" target="_blank" rel="noreferrer"><span class="recent-icon">${iconMarkup(x)}</span><span>${x[0]}</span></a>`).join("");
}
function recordRecent(item){
  if(!item||!item[2])return;
  data.recent=[item,...data.recent.filter(x=>x[2]!==item[2])].slice(0,10);
  save();
  renderRecent();
}
document.addEventListener("click",e=>{
  if(e.target.closest(".site-actions,.group-actions"))return;
  const link=e.target.closest(".site,.footer-site");
  if(!link)return;
  const kind=link.dataset.dragKind,group=Number(link.dataset.dragGroup),index=Number(link.dataset.dragIndex);
  const item=data[kind]?.[group]?.sites?.[index];
  if(item)recordRecent(item);
});

const THIRD_PARTY_BAIDU_HOT="https://v2.xxapi.cn/api/baiduhot";
function parseThirdPartyHot(payload){
  const raw=Array.isArray(payload)?payload:payload?.data?.content?.flatMap(group=>group.content||[])||payload?.data?.list||payload?.data?.data||payload?.data||payload?.result?.list||payload?.result||payload?.list||[];
  if(!Array.isArray(raw))return [];
  return raw.map(item=>{const sourceUrl=item.url||item.link||item.appUrl||item.rawUrl||"";return {title:item.title||item.word||item.name||item.query||item.desc||item.keyword||item.hotword||"",score:item.hotScore||item.hot||item.hotValue||item.score||item.num||item.value||"",url:sourceUrl.replace(/^https?:\/\/m\.baidu\.com/i,"https://www.baidu.com"),tag:item.tag||item.label||(item.hotTag==="1"?"新":item.hotTag==="3"?"热":"")}}).filter(item=>item.title);
}
async function loadThirdPartyHot(){
  const refresh=$("#hotRefresh");refresh.classList.add("is-loading");
  try{
    const response=await fetch(THIRD_PARTY_BAIDU_HOT,{cache:"no-store"});
    if(!response.ok)throw new Error("third-party hot feed unavailable");
    const payload=await response.json(),items=parseThirdPartyHot(payload);
    if(!items.length)throw new Error("unexpected hot feed response");
    hotItems=items.sort((a,b)=>Number(b.score||0)-Number(a.score||0));hotPage=0;renderReferenceHot();
  }catch{hotItems=[];hotPage=0;renderReferenceHot()}finally{refresh.classList.remove("is-loading")}
}
for(const id of ["hotPrev","hotNext","hotRefresh"]){const old=$("#"+id),fresh=old.cloneNode(true);old.replaceWith(fresh)}
$("#hotPrev").addEventListener("click",()=>{if(hotPage>0){hotPage--;renderReferenceHot()}});
$("#hotNext").addEventListener("click",()=>{if((hotPage+1)*8<hotItems.length){hotPage++;renderReferenceHot()}});
$("#hotRefresh").addEventListener("click",loadThirdPartyHot);
loadThirdPartyHot();

const THIRD_PARTY_WALLPAPER="https://v2.xxapi.cn/api/random4kPic?type=wallpaper";
function saveThirdPartyWallpaper(value){backgroundState={type:"bing",value};localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()}
async function requestThirdPartyWallpaper(){
  const response=await fetch(THIRD_PARTY_WALLPAPER,{cache:"no-store"});
  if(!response.ok)throw new Error("wallpaper request failed");
  const contentType=response.headers.get("content-type")||"";
  if(contentType.startsWith("image/")){const blob=await response.blob();return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}
  const payload=await response.json();if(payload.code&&payload.code!==200)throw new Error(payload.msg||"wallpaper unavailable");
  const value=typeof payload.data==="string"?payload.data:payload.url||payload.image||payload.imgurl||payload.data?.url||payload.data?.image||payload.data?.imgurl||payload.data?.link||payload.result?.url||payload.result?.image;
  if(!value||typeof value!=="string")throw new Error("invalid wallpaper response");return value;
}
document.addEventListener("click",e=>{const option=e.target.closest("#backgroundDialog .background-option");if(!option)return;e.stopPropagation();e.preventDefault();const type=option.dataset.background;if(type==="upload"){$("#backgroundInput").click();return}if(type==="bing"){option.disabled=true;option.classList.add("is-loading");requestThirdPartyWallpaper().then(saveThirdPartyWallpaper).catch(()=>{}).finally(()=>{option.disabled=false;option.classList.remove("is-loading")});return}backgroundState={type:"color",value:randomGradient()};localStorage.setItem(BACKGROUND_KEY,JSON.stringify(backgroundState));applyBackground()},{capture:true});

renderReferenceHot=function(){const pageSize=8,start=hotPage*pageSize,items=hotItems.slice(start,start+pageSize);$("#hotList").innerHTML=items.length?items.map((item,index)=>{const rank=start+index+1;return `<div class="hot-row"><span class="hot-rank hot-rank-${rank<=3?rank:"n"}">${rank}</span><a class="hot-title" href="${item.url||"https://www.baidu.com/s?wd="+encodeURIComponent(item.title)}" target="_blank" rel="noreferrer"><span class="hot-title-text">${item.title}</span>${item.tag?`<span class="hot-tag hot-tag-${item.tag==="新"?"new":"hot"}">${item.tag}</span>`:""}</a>${item.score?`<span class="hot-score">${item.score}</span>`:""}</div>`}).join(""):"<div class=\"hot-loading\">当前无数据</div>";$("#hotPrev").disabled=hotPage===0||!items.length;$("#hotNext").disabled=!items.length||start+pageSize>=hotItems.length};
hotItems=[];hotPage=0;renderReferenceHot();loadThirdPartyHot();
